spring.application.name=session13


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=04122001


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

cloud-name=dud5j9zqd
api-key=593427543625779
api-secret=3_iAi_HC8kckU6INvYfrjzTVFJY


spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranleanhkhoa041221@gmail.com
spring.mail.password=gwcx zugk rtsa cwrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



